win: fix ForcedIncludeFiles in msvs generator when used with precompiled headers
Caused errors like this:

111>..\build\precompile.cc : fatalerror C1083: Cannot open include file: 'r': No such file or directory

from this change:

https://codereview.chromium.org/29273003

but only on VS generator, all thanks to dumb list += string behaviour.

R=thakis@chromium.org

Review URL: https://codereview.chromium.org/28853006